[package]
name = "pac-human"
version = "0.1.0"
edition = "2021"
authors = ["nomlab"]

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
bevy = "0.9.0"
rand = "0.8.5"
